### ISSUE TITLE
feat: migrate to kubo-rpc-client

### ISSUE THREAD

**Issue by SgtPooki** [ipld/explore.ipld.io#117]
This codebase should remove js-ipfs and utilize only kubo-rpc-client (not ipfs-http-client) to talk to kubo

```[tasklist]
### Tasks
- [ ] Remove js-ipfs fallback
- [ ] Remove js-ipfs
- [ ] replace ipfs-http-client with kubo-rpc-client
- [ ] Update readme
```

Related to https://github.com/ipfs/ipfs-webui/issues/2079

**Comment by SgtPooki** [comment]
@rvagg @lidel any qualms against this issue? Does the deployed explore.ipld.io have a backing or remote kubo node to use if we remove js-ipfs?  

It looks like it's only deploying to fleek as a static website at this time, so I'm not sure how feasible this is.

**Comment by lidel** [comment]
explore.ipld.io has always been a static self contained website that works without local Kubo node.
 

if you want to remove js-ipfs, i see two options:
1. rewrite it so it uses Helia, 
2. and/or fetches raw blocks from public gateways (instead of ipfs.block.get, use  https://docs.ipfs.tech/reference/http/gateway/#trusted-vs-trustless)

breaking existing users by forcing them to install additional software and set up special CORS headers is not an option, i am afraid. 

think about it the other way around: local Kubo is optional, not the main backend :)

**Comment by SgtPooki** [comment]
makes sense! I threw this ticket together a while ago without thinking it through, and when I looked again recently figured completely removing js-ipfs wasn't necessarily where this should go; at least for my purposes.

there's still a story here for replacing ipfs-http-client->kubo communication. thanks for the confirmation 👍

**Comment by BigLep** [comment]
I changed the title and issue description (see history).  I think this is useful for showcasing Helia examples.
